// <auto-generated />
namespace lurin.meurhonline.infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ajustecartaoponto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajustecartaoponto));
        
        string IMigrationMetadata.Id
        {
            get { return "202103120057077_ajuste-cartao-ponto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
