// <auto-generated />
namespace lurin.meurhonline.infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ajustesholeriteempresaid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajustesholeriteempresaid));
        
        string IMigrationMetadata.Id
        {
            get { return "202103131804507_ajustes-holerite-empresaid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
