// <auto-generated />
namespace lurin.meurhonline.infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _20210923_FornecedorHolerite_AddColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210923_FornecedorHolerite_AddColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "202109231834341_20210923_FornecedorHolerite_AddColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
