// <auto-generated />
namespace lurin.meurhonline.infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class OperadoraVTBandeiraCartaoDataCadastro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OperadoraVTBandeiraCartaoDataCadastro));
        
        string IMigrationMetadata.Id
        {
            get { return "202103171641034_OperadoraVTBandeiraCartao-DataCadastro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
