// <auto-generated />
namespace lurin.meurhonline.infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _20211014_DivergenciaDetalhe_AddColumns_JustificativaDivergenciaID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20211014_DivergenciaDetalhe_AddColumns_JustificativaDivergenciaID));
        
        string IMigrationMetadata.Id
        {
            get { return "202110141920304_20211014_DivergenciaDetalhe_AddColumns_JustificativaDivergenciaID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
