// <auto-generated />
namespace lurin.meurhonline.infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class importacaoabsenteismo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(importacaoabsenteismo));
        
        string IMigrationMetadata.Id
        {
            get { return "202103161633313_importacao-absenteismo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
